// data.jsx — works, series, journey

const SERIES = [
  { id: "karbala",  num: "I",   name: "The Day of Ashura",        blurb: "Three works rendered from the long afternoon of the tenth day." },
];

const WORKS = [
  {
    id: "w01", title: "The Lone Rider", year: 2023, series: "karbala",
    medium: "Coloured pencil & pastel on paper", dims: "approx. 76 × 91 cm",
    edition: "Unique",
    arabic: "الفارس الوحيد",
    image: "art/the-tenth-day.jpg", aspect: "1154/1419",
    body: "A solitary horseman moves through a field of grief and fire. The companions fall around him in colour — saffron, crimson, ochre — while smoke gathers above the plain.",
    moment: "The afternoon of the 10th of Muharram, 61 AH — Karbala.",
    symbols: ["sacrifice", "smoke", "companions"],
    palette: ["#1a1614", "#a8864b", "#e8dcc4"], size: "l",
  },
  {
    id: "w02", title: "The Standard Bearer", year: 2022, series: "karbala",
    medium: "Acrylic on canvas", dims: "approx. 60 × 76 cm",
    edition: "Unique",
    arabic: "حامل الراية",
    image: "art/the-standard-bearer.jpg", aspect: "1188/1600",
    body: "The green standard rises above the camp, held by the rider who turns back toward the women and the child. The tents stand. The desert holds its breath.",
    moment: "Before the departure — the standard raised at the edge of the camp.",
    symbols: ["banner", "tent", "farewell"],
    palette: ["#2a2520", "#3d6b3a", "#d8c9a8"], size: "w",
  },
  {
    id: "w03", title: "The Ambush of the Caravan", year: 2024, series: "karbala",
    medium: "Acrylic on canvas", dims: "approx. 60 × 76 cm",
    edition: "Unique",
    arabic: "كمين القافلة",
    image: "art/the-ambush.jpg", aspect: "1203/1600",
    body: "A camel-borne litter under a green canopy is set upon by riders. Cloaks billow crimson; swords flash; the sky burns yellow-green with dust and smoke.",
    moment: "The captives' march — the road from Karbala to Kufa.",
    symbols: ["caravan", "ambush", "wind"],
    palette: ["#1f2a1a", "#7a1e1e", "#c2a574"], size: "m",
  },
  {
    id: "w04", title: "The Crimson Council", year: 2023, series: "karbala",
    medium: "Acrylic on canvas", dims: "approx. 60 × 76 cm", edition: "Unique",
    arabic: "المجلس القرمزي",
    image: "art/p04.jpg", aspect: "1199/1600",
    body: "A figure in scarlet kneels at a small fire surrounded by elders and standards. The sky is the colour of the moment before resolve becomes inevitable.",
    moment: "The night before — the council of companions.",
    symbols: ["fire", "council", "resolve"],
    palette: ["#7a1e1e", "#3a1010", "#c2a574"], size: "l",
  },
  {
    id: "w05", title: "The Mourner Returning", year: 2023, series: "karbala",
    medium: "Coloured pencil & pastel on paper", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "العائد الحزين",
    image: "art/p05.jpg", aspect: "1148/1600",
    body: "A figure walks back from the field carrying a small body. The cloak is a long crimson wound. In the distance, the banners of the survivors recede.",
    moment: "After the battle — the slow walk back to the camp.",
    symbols: ["mourning", "child", "return"],
    palette: ["#a8864b", "#7a1e1e", "#d8c9a8"], size: "p",
  },
  {
    id: "w06", title: "The Sword Held Still", year: 2024, series: "karbala",
    medium: "Acrylic on board", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "السيف الساكن",
    image: "art/p06.jpg", aspect: "1181/1600",
    body: "A veiled figure cradles a sheathed sword across both hands. The stillness of the painting is its argument: weapons may be held without being raised.",
    moment: "Before the morning prayer.",
    symbols: ["sword", "stillness", "vow"],
    palette: ["#a8864b", "#3d6b3a", "#e8dcc4"], size: "s",
  },
  {
    id: "w07", title: "The Crossing", year: 2024, series: "karbala",
    medium: "Oil on board", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "العبور",
    image: "art/p07.jpg", aspect: "1199/1600",
    body: "A horseman in green crosses a moonlit river beneath a full moon. The water around the horse's hooves is luminous; the night beyond is black.",
    moment: "A crossing — water permitted, briefly, by the night.",
    symbols: ["water", "moon", "passage"],
    palette: ["#0e1b3a", "#3d6b3a", "#d8c9a8"], size: "t",
  },
  {
    id: "w08", title: "The Weight Unspoken", year: 2023, series: "karbala",
    medium: "Watercolour on paper", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "العبء الصامت",
    image: "art/p08.jpg", aspect: "1199/1600",
    body: "A robed figure raises a scythe-like blade above another seated and veiled. The painting holds the moment before the descent — and refuses to release it.",
    moment: "The threshold.",
    symbols: ["threshold", "blade", "veil"],
    palette: ["#a8864b", "#3d6b3a", "#e8dcc4"], size: "m",
  },
  {
    id: "w09", title: "The Doves at the Camp", year: 2024, series: "karbala",
    medium: "Acrylic on canvas", dims: "approx. 60 × 76 cm", edition: "Unique",
    arabic: "الحمائم",
    image: "art/p09.jpg", aspect: "1199/1600",
    body: "A robed figure under a crescent moon watches doves gather at her feet — luminous, blue and gold, refusing to leave the empty camp.",
    moment: "After the camp is emptied — the night birds remain.",
    symbols: ["doves", "moon", "vigil"],
    palette: ["#1a2438", "#a8864b", "#3d6b6b"], size: "p",
  },
  {
    id: "w10", title: "The Lion-Tamer", year: 2024, series: "karbala",
    medium: "Graphite on paper", dims: "approx. 70 × 40 cm", edition: "Unique",
    arabic: "صاحب الأسود",
    image: "art/p10.jpg", aspect: "1600/920",
    body: "A figure walks between two great lions through the long grass. A reference to the old story — that the wild creatures recognised the heir before the people did.",
    moment: "On the road — the wilderness recognises what the city refuses to.",
    symbols: ["lion", "recognition", "passage"],
    palette: ["#2a2520", "#4a4138", "#d8c9a8"], size: "w",
  },
  {
    id: "w11", title: "The Tent of the Watchman", year: 2022, series: "karbala",
    medium: "Graphite on paper", dims: "approx. 30 × 50 cm", edition: "Unique",
    arabic: "خيمة الحارس",
    image: "art/p11.jpg", aspect: "935/1600",
    body: "A figure walks beneath the torn tent-cloth toward an arched opening. Behind, a brazier. Beyond, a city that may or may not still be standing.",
    moment: "After the burning of the tents — at first light.",
    symbols: ["tent", "threshold", "watch"],
    palette: ["#1a1614", "#4a4138", "#d8c9a8"], size: "s",
  },
  {
    id: "w12", title: "The Mourner Walks", year: 2023, series: "karbala",
    medium: "Coloured pencil & pastel on paper", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "السائرة الحزينة",
    image: "art/p12.jpg", aspect: "1199/1600",
    body: "A second study of the returning mourner — cloak heavier, ground softer, the body in her arms more present than the body that carries it.",
    moment: "After — the road back.",
    symbols: ["mourning", "carrying", "road"],
    palette: ["#a8864b", "#7a1e1e", "#d8c9a8"], size: "m",
  },
  {
    id: "w13", title: "The Slayer Pauses", year: 2024, series: "karbala",
    medium: "Coloured pencil on paper", dims: "approx. 50 × 70 cm", edition: "Unique",
    arabic: "وقفة القاتل",
    image: "art/p13.jpg", aspect: "1105/1600",
    body: "Above a fallen body in a field of stones, the slayer turns his face away — the painting more interested in his refusal to look than in the act itself.",
    moment: "The instant after.",
    symbols: ["aftermath", "refusal", "stones"],
    palette: ["#a8864b", "#7a1e1e", "#d8c9a8"], size: "p",
  },
];

const JOURNEY = [
  { step: "I",   title: "The Standard Raised", arabic: "حامل الراية", workId: "w02",
    body: "The green banner is raised above the camp. The rider turns back once more toward the tents — toward the women, the child, the small fires." },
  { step: "II",  title: "The Lone Rider", arabic: "الفارس الوحيد", workId: "w01",
    body: "On the plain, the companions fall in colour. The horseman moves alone through smoke and grief — the long afternoon of the tenth day." },
  { step: "III", title: "The Crimson Council", arabic: "المجلس القرمزي", workId: "w04",
    body: "On the eve, by a small fire, the companions gather. The sky burns the colour of resolve already taken." },
  { step: "IV",  title: "The Lone Rider", arabic: "الفارس الوحيد", workId: "w01",
    body: "On the plain, the companions fall in colour. The horseman moves alone through smoke and grief — the long afternoon of the tenth day." },
  { step: "V",   title: "The Caravan, Ambushed", arabic: "كمين القافلة", workId: "w03",
    body: "After. The captives are taken on the long road. A canopy is torn open; cloaks billow crimson against a sky burning yellow-green with dust." },
  { step: "VI",  title: "The Mourner Returning", arabic: "العائد الحزين", workId: "w05",
    body: "A figure walks back from the field, carrying a small body. The banners recede, but the weight does not." },
  { step: "VII", title: "The Doves Remain", arabic: "الحمائم", workId: "w09",
    body: "Under a crescent moon, the camp is empty — but the night birds gather, luminous, refusing to leave." },
];

window.SERIES = SERIES;
window.WORKS = WORKS;
window.JOURNEY = JOURNEY;
